import type { ResearchProfileContract } from "./researchProfileContract"

export const PHARMA_RESEARCH_PROFILE_V1 = {
  profileCode: "PHARMA",
  profileVersion: "PHARMA_V1",
  displayName: "Pharmaceuticals",
  metrics: [
    {
      metricCode: "PHARMA_REVENUE_GROWTH_HISTORY",
      dimension: "GROWTH",
      applicability: "APPLICABLE",
      requirementLevel: "MANDATORY",
      periodTypes: ["YEAR", "QUARTER"],
      history: { minimumObservations: 3, preferredObservations: 5, historyUnit: "YEAR" },
      direction: "HIGHER_BETTER",
      normalizationMethod: "multi_period_growth_with_consistency",
      calculationOwner: "PORTFOLIOAI",
      sourceContract: "Reviewed canonical revenue history; no single TTM snapshot may satisfy this metric.",
      freshnessPolicy: "Latest reported annual/quarterly evidence must be current for the most recent completed reporting period.",
      scoreCurveVersion: null,
      reasonCodeNamespace: "PHARMA_GROWTH",
      conditionCode: null,
    },
    {
      metricCode: "PHARMA_OPERATING_MARGIN_HISTORY",
      dimension: "QUALITY",
      applicability: "APPLICABLE",
      requirementLevel: "MANDATORY",
      periodTypes: ["QUARTER", "TTM", "YEAR"],
      history: { minimumObservations: 8, preferredObservations: 12, historyUnit: "QUARTER" },
      direction: "RANGE",
      normalizationMethod: "margin_level_trend_and_consistency",
      calculationOwner: "PORTFOLIOAI",
      sourceContract: "Reviewed EBITDA/operating-margin history using semantically consistent periods.",
      freshnessPolicy: "Latest completed quarter/TTM must be available and not stale.",
      scoreCurveVersion: null,
      reasonCodeNamespace: "PHARMA_MARGIN",
      conditionCode: null,
    },
    {
      metricCode: "PHARMA_ROCE_HISTORY",
      dimension: "QUALITY",
      applicability: "APPLICABLE",
      requirementLevel: "MANDATORY",
      periodTypes: ["YEAR"],
      history: { minimumObservations: 3, preferredObservations: 5, historyUnit: "YEAR" },
      direction: "HIGHER_BETTER",
      normalizationMethod: "level_trend_and_consistency",
      calculationOwner: "PORTFOLIOAI",
      sourceContract: "Reviewed annual ROCE history with consistent calculation semantics.",
      freshnessPolicy: "Latest completed annual period must be available.",
      scoreCurveVersion: null,
      reasonCodeNamespace: "PHARMA_ROCE",
      conditionCode: null,
    },
    {
      metricCode: "PHARMA_PAT_EPS_HISTORY",
      dimension: "GROWTH",
      applicability: "APPLICABLE",
      requirementLevel: "MANDATORY",
      periodTypes: ["YEAR", "QUARTER"],
      history: { minimumObservations: 3, preferredObservations: 5, historyUnit: "YEAR" },
      direction: "HIGHER_BETTER",
      normalizationMethod: "profit_and_eps_growth_consistency",
      calculationOwner: "PORTFOLIOAI",
      sourceContract: "Reviewed PAT/EPS history; one current-period value is insufficient.",
      freshnessPolicy: "Latest completed annual/quarterly evidence must be current.",
      scoreCurveVersion: null,
      reasonCodeNamespace: "PHARMA_EARNINGS",
      conditionCode: null,
    },
    {
      metricCode: "PHARMA_CASH_CONVERSION_HISTORY",
      dimension: "EARNINGS_CASH_QUALITY",
      applicability: "APPLICABLE",
      requirementLevel: "MANDATORY",
      periodTypes: ["YEAR"],
      history: { minimumObservations: 3, preferredObservations: 5, historyUnit: "YEAR" },
      direction: "HIGHER_BETTER",
      normalizationMethod: "cfo_pat_and_fcf_conversion",
      calculationOwner: "PORTFOLIOAI",
      sourceContract: "Matched-period CFO, PAT and capex/FCF evidence. CFO alone does not satisfy the contract.",
      freshnessPolicy: "Latest completed annual period must be available.",
      scoreCurveVersion: null,
      reasonCodeNamespace: "PHARMA_CASH",
      conditionCode: null,
    },
    {
      metricCode: "PHARMA_BALANCE_SHEET_LEVERAGE",
      dimension: "FINANCIAL_STRENGTH",
      applicability: "APPLICABLE",
      requirementLevel: "MANDATORY",
      periodTypes: ["YEAR", "POINT_IN_TIME"],
      history: { minimumObservations: 3, preferredObservations: 5, historyUnit: "YEAR" },
      direction: "LOWER_BETTER",
      normalizationMethod: "net_debt_leverage_and_interest_cover",
      calculationOwner: "PORTFOLIOAI",
      sourceContract: "Reviewed debt, cash and operating-earnings evidence with matched periods.",
      freshnessPolicy: "Latest balance-sheet period must be current.",
      scoreCurveVersion: null,
      reasonCodeNamespace: "PHARMA_BALANCE_SHEET",
      conditionCode: null,
    },
    {
      metricCode: "PHARMA_REGULATORY_SITE_STATUS",
      dimension: "RISK",
      applicability: "CONDITIONAL",
      requirementLevel: "MANDATORY",
      periodTypes: ["EVENT"],
      history: { minimumObservations: 1, preferredObservations: 1, historyUnit: "EVENT" },
      direction: "CUSTOM",
      normalizationMethod: "official_regulatory_event_state",
      calculationOwner: "OFFICIAL_EVIDENCE",
      sourceContract: "Official regulator/issuer evidence for materially regulated export manufacturing sites where exposure exists.",
      freshnessPolicy: "Current unresolved actions plus latest material inspection/remediation state must be represented.",
      scoreCurveVersion: null,
      reasonCodeNamespace: "PHARMA_REGULATORY",
      conditionCode: "REGULATED_EXPORT_EXPOSURE",
    },
    {
      metricCode: "PHARMA_DOMESTIC_REVENUE_GROWTH",
      dimension: "GROWTH",
      applicability: "CONDITIONAL",
      requirementLevel: "IMPORTANT",
      periodTypes: ["YEAR", "QUARTER"],
      history: { minimumObservations: 4, preferredObservations: 8, historyUnit: "QUARTER" },
      direction: "HIGHER_BETTER",
      normalizationMethod: "segment_growth_trend",
      calculationOwner: "PORTFOLIOAI",
      sourceContract: "Reviewed domestic-formulations revenue evidence where separately disclosed.",
      freshnessPolicy: "Latest completed reporting period when disclosed.",
      scoreCurveVersion: null,
      reasonCodeNamespace: "PHARMA_DOMESTIC",
      conditionCode: "DOMESTIC_BUSINESS_MATERIAL",
    },
    {
      metricCode: "PHARMA_EXPORT_US_REVENUE_GROWTH",
      dimension: "GROWTH",
      applicability: "CONDITIONAL",
      requirementLevel: "IMPORTANT",
      periodTypes: ["YEAR", "QUARTER"],
      history: { minimumObservations: 4, preferredObservations: 8, historyUnit: "QUARTER" },
      direction: "HIGHER_BETTER",
      normalizationMethod: "segment_growth_trend",
      calculationOwner: "PORTFOLIOAI",
      sourceContract: "Reviewed export/US revenue evidence where the exposure is material and separately disclosed.",
      freshnessPolicy: "Latest completed reporting period when disclosed.",
      scoreCurveVersion: null,
      reasonCodeNamespace: "PHARMA_EXPORT",
      conditionCode: "REGULATED_EXPORT_EXPOSURE",
    },
    {
      metricCode: "PHARMA_RND_INTENSITY",
      dimension: "BUSINESS_DURABILITY",
      applicability: "APPLICABLE",
      requirementLevel: "IMPORTANT",
      periodTypes: ["YEAR"],
      history: { minimumObservations: 3, preferredObservations: 5, historyUnit: "YEAR" },
      direction: "RANGE",
      normalizationMethod: "rnd_to_revenue_with_productivity_context",
      calculationOwner: "PORTFOLIOAI",
      sourceContract: "Reviewed R&D expense and revenue history. High spend is not automatically positive without productivity context.",
      freshnessPolicy: "Latest completed annual period must be available.",
      scoreCurveVersion: null,
      reasonCodeNamespace: "PHARMA_RND",
      conditionCode: null,
    },
    {
      metricCode: "PHARMA_PIPELINE_LAUNCH_APPROVAL_EVIDENCE",
      dimension: "BUSINESS_DURABILITY",
      applicability: "APPLICABLE",
      requirementLevel: "IMPORTANT",
      periodTypes: ["EVENT"],
      history: { minimumObservations: 1, preferredObservations: 4, historyUnit: "EVENT" },
      direction: "INFORMATIONAL",
      normalizationMethod: "evidence_weighted_pipeline_and_approval_state",
      calculationOwner: "CANONICAL_PROVIDER_EVIDENCE",
      sourceContract: "Issuer/official/reviewed research evidence for material launches, approvals and pipeline milestones.",
      freshnessPolicy: "Latest material events within the current research window.",
      scoreCurveVersion: null,
      reasonCodeNamespace: "PHARMA_PIPELINE",
      conditionCode: null,
    },
    {
      metricCode: "PHARMA_OWNERSHIP_GOVERNANCE",
      dimension: "GOVERNANCE",
      applicability: "APPLICABLE",
      requirementLevel: "IMPORTANT",
      periodTypes: ["QUARTER", "EVENT"],
      history: { minimumObservations: 4, preferredObservations: 8, historyUnit: "QUARTER" },
      direction: "CUSTOM",
      normalizationMethod: "ownership_trend_pledge_and_governance_event_overlay",
      calculationOwner: "PORTFOLIOAI",
      sourceContract: "Reviewed ownership history plus governance-event evidence; promoter absence is not automatically negative.",
      freshnessPolicy: "Latest completed shareholding quarter and current material governance events.",
      scoreCurveVersion: null,
      reasonCodeNamespace: "PHARMA_GOVERNANCE",
      conditionCode: null,
    },
    {
      metricCode: "PHARMA_VALUATION_CONTEXT",
      dimension: "VALUATION",
      applicability: "APPLICABLE",
      requirementLevel: "IMPORTANT",
      periodTypes: ["TTM", "POINT_IN_TIME", "YEAR"],
      history: { minimumObservations: 1, preferredObservations: 5, historyUnit: "YEAR" },
      direction: "CUSTOM",
      normalizationMethod: "pe_ev_ebitda_fcf_yield_vs_history_and_peers",
      calculationOwner: "PORTFOLIOAI",
      sourceContract: "Canonical valuation evidence using authoritative market price plus reviewed earnings/cash inputs; provider valuation labels are evidence, not authority over market price.",
      freshnessPolicy: "Valuation must use current authoritative market price and current earnings evidence.",
      scoreCurveVersion: null,
      reasonCodeNamespace: "PHARMA_VALUATION",
      conditionCode: null,
    },
  ],
} as const satisfies ResearchProfileContract
