/** Existing canonical observation aliases. Provider hints do not add aliases here. */
export const P7_IC_CANONICAL_REQUIREMENT_METRICS: Readonly<Record<string, readonly string[]>> = {
  ROCE_OR_ROIC: ["ROCE_ANNUAL", "ROCE_MANAGEMENT_ANNUAL"],
  OPERATING_MARGIN_HISTORY: ["OPM_TTM", "OPERATING_PROFIT_QUARTER"],
  GROSS_OPERATING_MARGIN_HISTORY: ["OPM_TTM"],
  REVENUE_GROWTH_MULTI_PERIOD: ["REVENUE_ANNUAL", "REVENUE_TTM"],
  NET_PROFIT_GROWTH_MULTI_PERIOD: ["NET_PROFIT_TTM", "PAT_ATTRIBUTABLE_ANNUAL"],
  EPS_GROWTH_MULTI_PERIOD: ["EPS_DILUTED_ANNUAL", "EPS_DILUTED"],
  CFO_OR_FCF_CONVERSION: ["CFO_ANNUAL", "FREE_CASH_FLOW_ANNUAL"],
  NET_CASH_OR_LEVERAGE: ["NET_DEBT_EBITDA_ANNUAL", "TOTAL_DEBT_ANNUAL", "DEBT_EQUITY"],
  // Implied upside is a percentage. It must never satisfy a P/E-ratio requirement.
  PE: ["PE_TTM"],
  GROSS_NPA_PERCENT: ["GROSS_NPA_PERCENT"], NET_NPA_PERCENT: ["NET_NPA_PERCENT"],
  // BANK profile requirement names refer to these established percentage primitives.
  GROSS_NPA: ["GROSS_NPA_PERCENT"], NET_NPA: ["NET_NPA_PERCENT"],
  EPS_GROWTH_YOY: ["EPS_GROWTH_YOY"], ADVANCES_GROWTH_YOY: ["ADVANCES_GROWTH_YOY"],
  DEPOSITS_GROWTH_YOY: ["DEPOSITS_GROWTH_YOY"],
  CET1_RATIO: ["CET1_RATIO", "SFB_PRUDENTIAL_CET1"],
  CAPITAL_ADEQUACY_RATIO: ["CAPITAL_ADEQUACY_RATIO", "SFB_PRUDENTIAL_TOTAL_CRAR"],
}
