import {describe,expect,it} from "vitest"
import {assertExpectedStockId,parseDocumentAppearances,parseMcpResult,parseOverview,parseOwnership,parseSearchCandidates,verifyIdentity} from "./trendlyne"

const search=`status: success\ndata:\n  name | nse_code | bse_code | isin | entity_type | sector | industry\n  Samvardhana Motherson International Ltd. | MOTHERSON | 517334 | INE775A01035 | stock | Auto | Parts\n  Motherson Sumi Wiring India Ltd. | MSUMI | 543498 | INE0FS801015 | stock | Auto | Parts`
const overview=`fundamentalData:\n  name | value | color | st | lt | unit | title | unique_name\n  Market Cap | 100.25 | x | x | x | Cr. | Market Capitalization | MCAP_Q\n  Price to Book Value Adjusted | None | x | x | x | ratio | Price to Book | PBV_A\nSWOTData:\nstockData:\n  Samvardhana Motherson International Ltd., 878, Equity, MOTHERSON, 517334, INE775A01035, 1, 1, 1, x, x, x, x, x, x, x, x, Auto Parts`
describe("Trendlyne adapter contract",()=>{
  it("accepts only exact verified identity and keeps provider stock id",()=>expect(verifyIdentity({name:"Samvardhana Motherson International Ltd.",symbol:"MOTHERSON",isin:"INE775A01035",bseCode:"517334"},parseSearchCandidates(search),parseOverview(overview)).stockId).toBe("878"))
  it("accepts a canonical ticker placeholder only with exact symbol and ISIN evidence",()=>expect(verifyIdentity({name:"MOTHERSON",symbol:"MOTHERSON",isin:"INE775A01035",bseCode:null},parseSearchCandidates(search),parseOverview(overview)).stockId).toBe("878"))
  it("does not confuse MOTHERSON and MSUMI",()=>expect(()=>verifyIdentity({name:"Motherson Sumi Wiring India Ltd.",symbol:"MOTHERSON",isin:"INE0FS801015",bseCode:"543498"},parseSearchCandidates(search),parseOverview(overview))).toThrow(/AMBIGUOUS|CONFLICTING/))
  it("supports BBOX candidate fallback only through exact ISIN",()=>{const c=parseSearchCandidates(`data:\n  name | nse_code | bse_code | isin | entity_type | sector | industry\n  Black Box Ltd. |  | 500463 | INE676A01027 | stock | IT | Services`); expect(c[0].isin).toBe("INE676A01027")})
  it("preserves nulls and quarantines adjusted PBV",()=>{const m=parseOverview(overview).metrics; expect(m.some(x=>x.code==="PBV_ADJUSTED_PROVIDER")).toBe(false); expect(m[0].value).toBe("100.25")})
  it("keeps adjusted PBV separate and explicitly conflicting",()=>{const changed=overview.replace("None","1.75");expect(parseOverview(changed).metrics).toContainEqual(expect.objectContaining({code:"PBV_ADJUSTED_PROVIDER",evidenceStatus:"CONFLICTING"}))})
  it("does not equate EBITDA, operating profit, or unreviewed margins",()=>{const changed=overview.replace("SWOTData:","  EBITDA | 10 | x | x | x | Cr | EBITDA | EBITDA_PROVIDER\n  Operating Profit | 9 | x | x | x | Cr | Operating Profit | OP_PROVIDER\nSWOTData:");expect(parseOverview(changed).metrics.map(x=>x.code)).not.toEqual(expect.arrayContaining(["EBITDA","OPERATING_PROFIT"]))})
  it("does not fabricate period, scope, or currency",()=>{const changed=overview.replace("SWOTData:","  Cash From Operating Activity | 8 | x | x | x | Cr | CFO | CFO_A\nSWOTData:");const cfo=parseOverview(changed).metrics.find(x=>x.code==="CFO_ANNUAL");expect(cfo?.periodType).toBeNull();expect(cfo).not.toHaveProperty("currency");expect(cfo).not.toHaveProperty("consolidationScope")})
  it("rejects unexpected semantic-search securities",()=>expect(()=>assertExpectedStockId("878","2229")).toThrow("UNEXPECTED"))
  it("maps aggregate ownership with reporting dates and denominators",()=>{const rows=parseOwnership(`shBarChartData:\n  Promoter:\n    ["Quarter","Promoter Holding (%)"], ["Jun 2026",55.5,"55.5 %"]\n  FII:\n    ["Quarter","Holding (%)"], ["Jun 2026",10.1,"10.1 %"]\nPromoter Pledge: 2.5`); expect(rows).toContainEqual({code:"SHAREHOLDING_PROMOTER_PERCENT",value:"55.5",periodEnd:"2026-06-30",unit:"PERCENT"}); expect(rows).toContainEqual({code:"SHAREHOLDING_PROMOTER_PLEDGE_PERCENT",value:"2.5",periodEnd:null,unit:"PERCENT_OF_PROMOTER_HOLDING"})})
  it("retains stable document headers and discards bodies",()=>expect(parseDocumentAppearances(JSON.stringify({markdown_data:"2220298|HDFC Bank Ltd.|HDFCBANK|533|Annual Report|2026-04-17\nprivate document body"}))[0]).toEqual({providerDocumentId:"2220298",companyName:"HDFC Bank Ltd.",symbol:"HDFCBANK",stockId:"533",publishedAt:"2026-04-17T00:00:00Z",documentType:"ANNUAL_REPORT"}))
  it("accepts the quoted live provider-document header shape",()=>expect(parseDocumentAppearances(JSON.stringify({markdown_data:"\"2220298|HDFC Bank Ltd.|HDFCBANK|533|Annual Report|2026-04-17\\nprivate document body"}))).toHaveLength(1))
  it("deduplicates repeated chunks for one provider document",()=>expect(parseDocumentAppearances(JSON.stringify({markdown_data:"2220298|HDFC Bank Ltd.|HDFCBANK|533|Annual Report|2026-04-17\nbody\n2220298|HDFC Bank Ltd.|HDFCBANK|533|Annual Report|2026-04-17\nbody two"}))).toHaveLength(1))
  it("fails safely when required overview identity is malformed",()=>expect(()=>parseOverview("fundamentalData: invalid")).toThrow("omitted stockData"))
  it("parses event-prefixed streamable HTTP responses",()=>expect(parseMcpResult("event: message\r\ndata: {\"jsonrpc\":\"2.0\",\"id\":1,\"result\":{\"ok\":true}}\r\n\r\n")).toEqual({ok:true}))
})
