import {describe,expect,it} from "vitest"
import {reconcileCanonicalAndReviewed,validateReviewedRequirementEvidence,type RequirementReview,type ReviewedDocumentSource,type ReviewedResearchDocument,type ReviewedSourceRecord} from "./v14-reviewed-evidence.ts"
import type {InputObservation,MetricDefinition} from "./p7-ic-input-validation.ts"

const owner="11111111-1111-4111-8111-111111111111",portfolio="22222222-2222-4222-8222-222222222222",security="33333333-3333-4333-8333-333333333333"
const now="2026-10-05T12:00:00Z",hash="a".repeat(64),docHash="b".repeat(64)
const quote="AKUMS|FY2026|ROCE Ann. %|12.50|CONSOLIDATED|published 2026-09-30"
const source:ReviewedSourceRecord={id:"raw",source_code:"COMPANY_EXCHANGE_FILING",retrieved_at:"2026-10-05T10:00:00Z",published_at:"2026-09-30T00:00:00Z",payload_hash:hash,raw_payload:{security_id:security,body:quote}}
const doc:ReviewedResearchDocument={id:"doc",security_id:security,reporting_period_start:"2025-04-01",reporting_period_end:"2026-03-31",reporting_period_type:"YEAR",published_at:"2026-09-30T00:00:00Z",canonical_content_hash:docHash,identity_status:"VERIFIED"}
const link:ReviewedDocumentSource={id:"link",research_document_id:"doc",source_record_id:"raw",source_code:"COMPANY_EXCHANGE_FILING",content_hash:docHash,source_status:"AVAILABLE",provider_document_id:"pdoc",source_url:"https://example.invalid/doc",retrieved_at:source.retrieved_at}
const def:MetricDefinition={code:"ROCE_ANNUAL",canonical_unit:"PERCENT",value_kind:"NUMERIC",is_active:true,freshness_seconds:2592000,definition:{selection:"REVIEWED",period_type:"YEAR",provider:"COMPANY_EXCHANGE_FILING",scope_guard:"CONSOLIDATED_ATTRIBUTABLE_TO_OWNERS"}}
const stable=(v:unknown):string=>Array.isArray(v)?"["+v.map(stable).join(",")+"]":v!==null&&typeof v==="object"?"{"+Object.entries(v as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>JSON.stringify(k)+":"+stable(x)).join(",")+"}":JSON.stringify(v)??"null"
const sha=async(v:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v)))).map(x=>x.toString(16).padStart(2,"0")).join("")
const reviewPayload=(r:RequirementReview)=>({portfolio_id:r.portfolio_id,security_id:r.security_id,requirement_code:r.requirement_code,review_kind:r.review_kind,decision:r.decision,source_record_id:r.source_record_id,research_document_id:r.research_document_id,provider_document_id:r.provider_document_id,source_payload_hash:r.source_payload_hash,supporting_quote:r.supporting_quote,period_start:r.period_start,period_end:r.period_end,period_type:r.period_type,unit:r.unit,currency:r.currency,consolidation_scope:r.consolidation_scope,published_at:r.published_at,retrieved_at:r.retrieved_at,fresh_through:r.fresh_through,review_version:r.review_version,reviewed_by:r.reviewed_by,reviewed_at:r.reviewed_at,supersedes_review_id:r.supersedes_review_id,metadata:r.metadata})
async function signed(patch:Partial<RequirementReview>={}){
 const r:RequirementReview={id:"44444444-4444-4444-8444-444444444444",portfolio_id:portfolio,security_id:security,requirement_code:"ROCE_OR_ROIC",review_kind:"OWNER_NUMERIC_REVIEW",decision:"ACCEPTED",source_record_id:"raw",research_document_id:"doc",provider_document_id:"pdoc",source_payload_hash:hash,supporting_quote:quote,period_start:"2025-04-01",period_end:"2026-03-31",period_type:"YEAR",unit:"PERCENT",currency:null,consolidation_scope:"CONSOLIDATED",published_at:"2026-09-30T00:00:00Z",retrieved_at:source.retrieved_at,fresh_through:"2026-10-20T10:00:00Z",review_version:"V1_4_REQUIREMENT_REVIEW_V2",reviewed_by:owner,reviewed_at:"2026-10-05T11:00:00Z",review_hash:"0".repeat(64),supersedes_review_id:null,metadata:{metric_code:"ROCE_ANNUAL",numeric_value:"12.50",source_binding:{kind:"TABLE_CELL",fragment:quote,metric_label:"ROCE Ann. %",period_label:"FY2026",exact_value:"12.50",entity_id:"AKUMS",period_start:"2025-04-01",period_end:"2026-03-31",period_type:"YEAR",scale:"1",conversion:"IDENTITY"}},...patch}
 return {...r,review_hash:await sha(stable(reviewPayload(r)))}
}
const validate=async(review:RequirementReview,family:"NUMERIC_SERIES"|"OWNERSHIP_4Q"|"TEXT_EVIDENCE_REVIEW"="NUMERIC_SERIES",minimum=1,overrides:Partial<Parameters<typeof validateReviewedRequirementEvidence>[0]>={})=>validateReviewedRequirementEvidence({portfolioId:portfolio,portfolioOwnerId:owner,securityId:security,requirementCode:review.requirement_code,family,metricCodes:["ROCE_ANNUAL"],minimum,reviews:[review],sources:[source],documents:[doc],documentSources:[link],definitions:[def],evaluationAsOfMs:Date.parse(now),sourceCutoffAtMs:Date.parse(now),...overrides})

describe("V1-4 reviewed evidence hardening",()=>{
 it("numeric family cannot fall through without metric/value metadata",async()=>{const r=await signed({metadata:{}});expect(await validate(r)).toMatchObject({state:"REVIEW_REQUIRED",reason:"NUMERIC_REVIEW_METRIC_VALUE_REQUIRED"})})
 it("binds exact value token: source 12.50 cannot support 2.50",async()=>{const r=await signed({metadata:{metric_code:"ROCE_ANNUAL",numeric_value:"2.50",source_binding:{kind:"TABLE_CELL",fragment:quote,metric_label:"ROCE Ann. %",period_label:"FY2026",exact_value:"2.50",entity_id:"AKUMS",period_start:"2025-04-01",period_end:"2026-03-31",period_type:"YEAR",scale:"1",conversion:"IDENTITY"}}});expect(await validate(r)).toMatchObject({state:"REVIEW_REQUIRED",reason:"NUMERIC_SOURCE_VALUE_NOT_EXACTLY_BOUND"})})
 it("rejects wrong normalized reporting year despite matching FY label",async()=>{const r=await signed({period_end:"2020-03-31",metadata:{metric_code:"ROCE_ANNUAL",numeric_value:"12.50",source_binding:{kind:"TABLE_CELL",fragment:quote,metric_label:"ROCE Ann. %",period_label:"FY2026",exact_value:"12.50",entity_id:"AKUMS",period_start:"2019-04-01",period_end:"2026-03-31",period_type:"YEAR",scale:"1",conversion:"IDENTITY"}}});expect(await validate(r)).toMatchObject({state:"REVIEW_REQUIRED",reason:"NUMERIC_SOURCE_PERIOD_MISMATCH"})})
 it("rejects missing ownership freshness",async()=>{const r=await signed({requirement_code:"OWNERSHIP_TREND_4Q",review_kind:"OWNER_OWNERSHIP_REVIEW",research_document_id:null,provider_document_id:null,period_start:null,period_end:"2026-06-30",period_type:"QUARTER",unit:"PERCENT",published_at:null,fresh_through:null,metadata:{numeric_value:"12.50",ownership_series:"PROMOTER",ownership_basis:"TOTAL_EQUITY"}});expect((await validate(r,"OWNERSHIP_4Q",4)).state).toBe("STALE")})
 it("rejects mixed ownership series",async()=>{const periods=["2025-09-30","2025-12-31","2026-03-31","2026-06-30"];const reviews:RequirementReview[]=[];for(let i=0;i<4;i++)reviews.push(await signed({id:"00000000-0000-4000-8000-00000000000"+i,requirement_code:"OWNERSHIP_TREND_4Q",review_kind:"OWNER_OWNERSHIP_REVIEW",research_document_id:null,provider_document_id:null,period_start:null,period_end:periods[i],period_type:"QUARTER",unit:"PERCENT",published_at:null,fresh_through:"2026-10-20T00:00:00Z",metadata:{numeric_value:"12.50",ownership_series:i===3?"FII":"PROMOTER",ownership_basis:"TOTAL_EQUITY"}}));expect(await validate(reviews[0]!,"OWNERSHIP_4Q",4,{reviews})).toMatchObject({state:"REVIEW_REQUIRED",reason:"OWNERSHIP_SERIES_OR_BASIS_MIXED"})})
 it("detects conflicting quarter values",async()=>{const a=await signed({requirement_code:"OWNERSHIP_TREND_4Q",review_kind:"OWNER_OWNERSHIP_REVIEW",research_document_id:null,provider_document_id:null,period_start:null,period_end:"2026-06-30",period_type:"QUARTER",unit:"PERCENT",published_at:null,fresh_through:"2026-10-20T00:00:00Z",metadata:{numeric_value:"12.50",ownership_series:"PROMOTER",ownership_basis:"TOTAL_EQUITY"}});const b=await signed({...a,id:"55555555-5555-4555-8555-555555555555",metadata:{numeric_value:"11.50",ownership_series:"PROMOTER",ownership_basis:"TOTAL_EQUITY"}});expect(await validate(a,"OWNERSHIP_4Q",1,{reviews:[a,b]})).toMatchObject({state:"CONFLICTING",reason:"OWNERSHIP_QUARTER_VALUE_CONFLICT"})})
 it("requires matching document content/source identity",async()=>{const r=await signed();expect(await validate(r,"NUMERIC_SERIES",1,{documentSources:[{...link,content_hash:"c".repeat(64)}]})).toMatchObject({reason:"DOCUMENT_SOURCE_CONTENT_HASH_MISMATCH"});expect(await validate(r,"NUMERIC_SERIES",1,{documentSources:[{...link,source_record_id:"other"}]})).toMatchObject({reason:"DOCUMENT_SOURCE_ASSOCIATION_NOT_UNIQUE"})})
 it("rejects unauthorized reviewer and invalid integrity",async()=>{const unauthorized=await signed({reviewed_by:"99999999-9999-4999-8999-999999999999"});expect(await validate(unauthorized)).toMatchObject({reason:"REVIEWER_NOT_AUTHORIZED_FOR_PORTFOLIO"});const r=await signed();expect(await validate({...r,review_hash:"f".repeat(64)})).toMatchObject({reason:"REVIEW_INTEGRITY_HASH_INVALID"})})
 it("malformed dates fail explicitly without throwing",async()=>{const r=await signed({period_end:"2026-99-99"});await expect(validate(r)).resolves.toMatchObject({state:"REVIEW_REQUIRED",reason:"REVIEW_NUMERIC_METADATA_INCOMPLETE"})})
 it("enforces supersession chronology and cutoff",async()=>{const prior=await signed({id:"66666666-6666-4666-8666-666666666666",reviewed_at:"2026-10-05T11:30:00Z"});const newer=await signed({id:"77777777-7777-4777-8777-777777777777",supersedes_review_id:prior.id,reviewed_at:"2026-10-05T11:00:00Z"});expect(await validate(prior,"NUMERIC_SERIES",1,{reviews:[prior,newer]})).toMatchObject({reason:"REVIEW_SUPERSESSION_CHAIN_INVALID"});const post=await signed({reviewed_at:"2026-10-06T00:00:00Z"});expect(await validate(post)).toMatchObject({reason:"REVIEW_CREATED_AFTER_SOURCE_CUTOFF"})})
 it("preserves canonical conflict over reviewed fallback",async()=>{const r=await signed();const reviewed=await validate(r);const row=(value:string):InputObservation=>({id:value,metric_code:"ROCE_ANNUAL",numeric_value:value,text_value:null,boolean_value:null,date_value:null,unit:"PERCENT",currency:null,consolidation_scope:"CONSOLIDATED",period_start:"2025-04-01",period_end:"2026-03-31",period_type:"YEAR",retrieved_at:"2026-10-05T09:00:00Z",fresh_until:"2026-10-20T09:00:00Z",published_at:"2026-09-30T00:00:00Z",evidence_status:"AVAILABLE",source_code:"COMPANY_EXCHANGE_FILING",source_record_id:"canon"});const x=reconcileCanonicalAndReviewed({canonicalRows:[row("10"),{...row("11"),id:"b"}],reviewed,definitions:[def],minimum:1,evaluationAsOfMs:Date.parse(now),sourceCutoffAtMs:Date.parse(now),family:"NUMERIC_SERIES"});expect(x.validation.state).toBe("CONFLICTING")})
 it("returns deterministic complete lineage",async()=>{const r=await signed();const x=await validate(r);expect(x?.lineage).toMatchObject({version:"V1_4_REVIEW_LEDGER_ADAPTER_V2",reviewIds:[r.id],sourceRecordIds:["raw"],researchDocumentIds:["doc"],documentSourceIds:["link"]})})
})