import {describe,expect,it} from "vitest"
import {createHash} from "node:crypto"
import {V1_4_MASTER_MAX_RESPONSE_BYTES,advanceMasterCaptureAccounting,captureByteStream,emptyMasterCaptureAccounting,scanMasterArtifact} from "./v14-master-capture.ts"
const enc=new TextEncoder()
const definitions=[{code:"A",displayName:"A",acceptedAliases:["NIFTY CAPITAL GOODS"],exchange:"NSE",instrumentType:"AMXIDX"},{code:"B",displayName:"B",acceptedAliases:["NIFTY CHEMICALS"],exchange:"NSE",instrumentType:"AMXIDX"}]
const codes=["A","B"]
async function* chunks(bytes:Uint8Array,size=7){for(let i=0;i<bytes.length;i+=size)yield bytes.slice(i,i+size)}
describe("V1-4 B0 streaming master capture",()=>{
 it("preserves exact bytes and hashes the raw stream",async()=>{const raw=enc.encode('[{"token":"1"}]'),parts:Uint8Array[]=[];const r=await captureByteStream(chunks(raw),{write:c=>{parts.push(c.slice())},close(){}});expect(r.byteLength).toBe(raw.length);expect(r.sha256).toBe(createHash("sha256").update(raw).digest("hex"));expect(Buffer.concat(parts.map(x=>Buffer.from(x)))).toEqual(Buffer.from(raw))})
 it("rejects an oversized response without silent truncation",async()=>{await expect(captureByteStream((async function*(){yield new Uint8Array(8);yield new Uint8Array(8)})(),{write(){},close(){}},10)).rejects.toThrow("P7_IC_BENCHMARK_MASTER_RESPONSE_TOO_LARGE")})
 it("rejects malformed JSON and non-array schema",async()=>{await expect(scanMasterArtifact({chunks:chunks(enc.encode('[{"a":1}')),definitions,requestedCodes:codes})).rejects.toThrow("P7_IC_BENCHMARK_MASTER_JSON_INVALID");await expect(scanMasterArtifact({chunks:chunks(enc.encode('{"a":1}')),definitions,requestedCodes:codes})).rejects.toThrow("P7_IC_BENCHMARK_MASTER_SCHEMA_INVALID")})
 it("preflights exact, unavailable and non-authorizing candidates from chunked bytes",async()=>{const raw=enc.encode(JSON.stringify([{token:"1",exch_seg:"NSE",symbol:"NIFTY CAPITAL GOODS",name:"NIFTY CAPITAL GOODS",instrumenttype:"AMXIDX"},{token:"2",exch_seg:"NSE",symbol:"NIFTY CHEM ETF",name:"NIFTY CHEMICALS",instrumenttype:"AMXETF"}]));const sha=createHash("sha256").update(raw).digest("hex");const r=await scanMasterArtifact({chunks:chunks(raw,3),definitions,requestedCodes:codes,expectedSha256:sha});expect(r.preflight[0]?.status).toBe("EXACT_MATCH");expect(r.preflight[1]?.status).toBe("UNAVAILABLE");expect(r.preflight[1]?.investigationCandidates[0]).toMatchObject({exactAliasAuthorized:false})})
 it("detects ambiguous exact aliases",async()=>{const raw=enc.encode(JSON.stringify([{token:"1",exch_seg:"NSE",symbol:"NIFTY CAPITAL GOODS",name:"NIFTY CAPITAL GOODS",instrumenttype:"AMXIDX"},{token:"2",exch_seg:"NSE",symbol:"NIFTY CAPITAL GOODS",name:"NIFTY CAPITAL GOODS",instrumenttype:"AMXIDX"}]));const r=await scanMasterArtifact({chunks:chunks(raw),definitions,requestedCodes:codes});expect(r.preflight[0]?.status).toBe("AMBIGUOUS")})
 it("keeps an interrupted attempt UNKNOWN until a response is independently established",()=>{const started=advanceMasterCaptureAccounting(emptyMasterCaptureAccounting(),{stage:"ATTEMPT_STARTED"});expect(started).toMatchObject({attemptStarted:true,responseReceived:false,capturePersisted:false,preflightCompleted:false,requestOutcome:"UNKNOWN"});const received=advanceMasterCaptureAccounting(started,{stage:"RESPONSE_RECEIVED",responseOk:true});expect(received.requestOutcome).toBe("SUCCEEDED");const complete=advanceMasterCaptureAccounting(received,{stage:"BODY_COMPLETE"});const persisted=advanceMasterCaptureAccounting(complete,{stage:"CAPTURE_PERSISTED"});expect(advanceMasterCaptureAccounting(persisted,{stage:"PREFLIGHT_COMPLETED"})).toMatchObject({capturePersisted:true,preflightCompleted:true})})
 it("streams a representative 32 MiB synthetic master without full-document JSON.parse",async()=>{const fillerName="X".repeat(900),row=JSON.stringify({token:"x",exch_seg:"NSE",symbol:"OTHER",name:fillerName,instrumenttype:"EQ"}),target=32*1024*1024;async function* synthetic(){yield enc.encode("[");let written=1,first=true,i=0;while(written<target){const s=(first?"":",")+row.replace('"x"',`"x${i++}"`),b=enc.encode(s);written+=b.length;first=false;yield b}yield enc.encode(','+JSON.stringify({token:"1",exch_seg:"NSE",symbol:"NIFTY CAPITAL GOODS",name:"NIFTY CAPITAL GOODS",instrumenttype:"AMXIDX"}));yield enc.encode(','+JSON.stringify({token:"2",exch_seg:"NSE",symbol:"NIFTY CHEMICALS",name:"NIFTY CHEMICALS",instrumenttype:"AMXIDX"}));yield enc.encode("]")}const r=await scanMasterArtifact({chunks:synthetic(),definitions,requestedCodes:codes,maxBytes:V1_4_MASTER_MAX_RESPONSE_BYTES});expect(r.byteLength).toBeGreaterThanOrEqual(target);expect(r.preflight.map(x=>x.status)).toEqual(["EXACT_MATCH","EXACT_MATCH"])})
})
