import {createHash} from "node:crypto"
import type {BenchmarkDefinition,IdentityPreflight,MasterRow,ResolvedIdentity} from "./v14-batch-b-contract.ts"
export const V1_4_MASTER_MAX_RESPONSE_BYTES=64*1024*1024
export const V1_4_MASTER_MAX_OBJECT_CHARS=1024*1024
export const V1_4_MASTER_FETCH_TIMEOUT_MS=30_000
export const V1_4_MASTER_STORAGE_TIMEOUT_MS=60_000
export interface ByteSink{write(c:Uint8Array):Promise<void>|void;close():Promise<void>|void;abort?(e:unknown):Promise<void>|void}

export type MasterCaptureStage="ATTEMPT_STARTED"|"RESPONSE_RECEIVED"|"BODY_COMPLETE"|"CAPTURE_PERSISTED"|"PREFLIGHT_COMPLETED"
export type MasterCaptureAccounting=Readonly<{attemptStarted:boolean;responseReceived:boolean;bodyComplete:boolean;capturePersisted:boolean;preflightCompleted:boolean;requestOutcome:"UNKNOWN"|"SUCCEEDED"|"FAILED"}>
export function emptyMasterCaptureAccounting():MasterCaptureAccounting{return{attemptStarted:false,responseReceived:false,bodyComplete:false,capturePersisted:false,preflightCompleted:false,requestOutcome:"UNKNOWN"}}
export function advanceMasterCaptureAccounting(state:MasterCaptureAccounting,event:{stage:MasterCaptureStage;responseOk?:boolean}):MasterCaptureAccounting{
 if(event.stage==="ATTEMPT_STARTED")return{...state,attemptStarted:true,requestOutcome:"UNKNOWN"}
 if(event.stage==="RESPONSE_RECEIVED"){if(!state.attemptStarted)throw new Error("P7_IC_BENCHMARK_MASTER_ACCOUNTING_ORDER_INVALID");return{...state,responseReceived:true,requestOutcome:event.responseOk===true?"SUCCEEDED":"FAILED"}}
 if(event.stage==="BODY_COMPLETE"){if(!state.responseReceived||state.requestOutcome!=="SUCCEEDED")throw new Error("P7_IC_BENCHMARK_MASTER_ACCOUNTING_ORDER_INVALID");return{...state,bodyComplete:true}}
 if(event.stage==="CAPTURE_PERSISTED"){if(!state.bodyComplete)throw new Error("P7_IC_BENCHMARK_MASTER_ACCOUNTING_ORDER_INVALID");return{...state,capturePersisted:true}}
 if(!state.capturePersisted)throw new Error("P7_IC_BENCHMARK_MASTER_ACCOUNTING_ORDER_INVALID");return{...state,preflightCompleted:true}
}
const txt=(v:unknown)=>typeof v==="string"&&v.trim()?v.trim():null
const norm=(v:unknown)=>txt(v)?.toUpperCase().replace(/&/gu," AND ").replace(/[^A-Z0-9]+/gu," ").trim().replace(/\s+/gu," ")??""
export async function* readableStreamChunks(s:ReadableStream<Uint8Array>){const r=s.getReader();try{for(;;){const n=await r.read();if(n.done)return;if(n.value.byteLength)yield n.value}}finally{r.releaseLock()}}
export async function captureByteStream(chunks:AsyncIterable<Uint8Array>,sink:ByteSink,max=V1_4_MASTER_MAX_RESPONSE_BYTES){const h=createHash("sha256");let n=0;try{for await(const c of chunks){n+=c.byteLength;if(n>max)throw new Error("P7_IC_BENCHMARK_MASTER_RESPONSE_TOO_LARGE");h.update(c);await sink.write(c)}await sink.close();return{byteLength:n,sha256:h.digest("hex")}}catch(e){await sink.abort?.(e);throw e}}
class ArrayParser{private d=new TextDecoder();private s:"START"|"FIRST"|"VALUE"|"SEP"|"DONE"="START";private o="";private depth=0;private str=false;private esc=false;rows=0;private onRow:(r:MasterRow)=>void;private max:number;constructor(onRow:(r:MasterRow)=>void,max=V1_4_MASTER_MAX_OBJECT_CHARS){this.onRow=onRow;this.max=max}push(c:Uint8Array){this.consume(this.d.decode(c,{stream:true}))}finish(){this.consume(this.d.decode());if(this.depth||this.str||this.s!=="DONE")throw new Error("P7_IC_BENCHMARK_MASTER_JSON_INVALID");return this.rows}private start(){this.o="{";this.depth=1;this.str=false;this.esc=false}private consume(v:string){for(const c of v){if(this.depth){this.o+=c;if(this.o.length>this.max)throw new Error("P7_IC_BENCHMARK_MASTER_OBJECT_TOO_LARGE");if(this.str){if(this.esc)this.esc=false;else if(c==="\\")this.esc=true;else if(c==='"')this.str=false;continue}if(c==='"')this.str=true;else if(c==="{")this.depth++;else if(c==="}"&&!--this.depth){let x:unknown;try{x=JSON.parse(this.o)}catch{throw new Error("P7_IC_BENCHMARK_MASTER_JSON_INVALID")}if(!x||typeof x!=="object"||Array.isArray(x))throw new Error("P7_IC_BENCHMARK_MASTER_SCHEMA_INVALID");this.onRow(x as MasterRow);this.rows++;this.o="";this.s="SEP"}continue}if(/\s/u.test(c))continue;if(this.s==="START"){if(c!=="[")throw new Error("P7_IC_BENCHMARK_MASTER_SCHEMA_INVALID");this.s="FIRST";continue}if(this.s==="FIRST"){if(c==="]"){this.s="DONE";continue}if(c!=="{")throw new Error("P7_IC_BENCHMARK_MASTER_SCHEMA_INVALID");this.start();continue}if(this.s==="VALUE"){if(c!=="{")throw new Error("P7_IC_BENCHMARK_MASTER_SCHEMA_INVALID");this.start();continue}if(this.s==="SEP"){if(c===","){this.s="VALUE";continue}if(c==="]"){this.s="DONE";continue}throw new Error("P7_IC_BENCHMARK_MASTER_JSON_INVALID")}throw new Error("P7_IC_BENCHMARK_MASTER_JSON_INVALID")}}}
type C={score:number;token:string|null;exchange:string;instrumentType:string;name:string|null;symbol:string|null;exactAliasAuthorized:false}
export function createStreamingPreflight(defs:readonly BenchmarkDefinition[],codes:readonly string[]){const st=(codes.map(code=>{const d=defs.find(x=>x.code===code);return d?{d,a:new Map(d.acceptedAliases.map(x=>[norm(x),x])),t:new Set(d.acceptedAliases.flatMap(x=>norm(x).split(" ")).filter(x=>x.length>=3)),e:new Map<string,ResolvedIdentity>(),c:[] as C[]}:null}))
return{consume(r:MasterRow){const ex=txt(r.exch_seg)?.toUpperCase()??"",it=txt(r.instrumenttype)?.toUpperCase()??"",token=txt(r.token),symbol=txt(r.symbol),name=txt(r.name),nn=norm(name),ns=norm(symbol),nc=norm((name??"")+" "+(symbol??""));for(const q of st){if(!q)continue;if(ex===q.d.exchange.toUpperCase()&&it===q.d.instrumentType.toUpperCase()&&token&&symbol){const na=q.a.get(nn),sa=q.a.get(ns),ma=na??sa;if(ma)q.e.set(token,{code:q.d.code,token,exchange:"NSE",symbol,name,instrumentType:"AMXIDX",matchedAlias:ma,matchedField:na?"name":"symbol",resolutionBasis:"EXACT_NORMALIZED_ALIAS"})}let score=0;for(const t of q.t)if(nc.includes(t))score++;if(score){q.c.push({score,token,exchange:ex,instrumentType:it,name,symbol,exactAliasAuthorized:false});q.c.sort((a,b)=>b.score-a.score||String(a.name??"").localeCompare(String(b.name??"")));if(q.c.length>12)q.c.length=12}}},finalize():readonly IdentityPreflight[]{return codes.map((code,i)=>{const q=st[i];if(!q)return{code,status:"UNAVAILABLE",identity:null,exactMatches:[],investigationCandidates:[],reason:"BENCHMARK_DEFINITION_MISSING"};const e=[...q.e.values()];if(e.length===1)return{code,status:"EXACT_MATCH",identity:e[0]!,exactMatches:e,investigationCandidates:q.c,reason:"EXACT_ACCEPTED_ALIAS_NSE_AMXIDX"};if(e.length>1)return{code,status:"AMBIGUOUS",identity:null,exactMatches:e,investigationCandidates:q.c,reason:"MULTIPLE_EXACT_ACCEPTED_ALIAS_NSE_AMXIDX"};return{code,status:"UNAVAILABLE",identity:null,exactMatches:[],investigationCandidates:q.c,reason:"NO_EXACT_ACCEPTED_ALIAS_NSE_AMXIDX"}})}}}
export async function scanMasterArtifact(i:{chunks:AsyncIterable<Uint8Array>;definitions:readonly BenchmarkDefinition[];requestedCodes:readonly string[];expectedSha256?:string|null;maxBytes?:number;maxObjectChars?:number}){const max=i.maxBytes??V1_4_MASTER_MAX_RESPONSE_BYTES,h=createHash("sha256"),p=createStreamingPreflight(i.definitions,i.requestedCodes),a=new ArrayParser(r=>p.consume(r),i.maxObjectChars);let n=0;for await(const c of i.chunks){n+=c.byteLength;if(n>max)throw new Error("P7_IC_BENCHMARK_MASTER_RESPONSE_TOO_LARGE");h.update(c);a.push(c)}const rows=a.finish();if(!rows)throw new Error("P7_IC_BENCHMARK_MASTER_SCHEMA_INVALID");const sha=h.digest("hex");if(i.expectedSha256&&sha!==i.expectedSha256)throw new Error("P7_IC_BENCHMARK_MASTER_HASH_MISMATCH");return{byteLength:n,sha256:sha,rowCount:rows,preflight:p.finalize()}}
