import {createClient} from "https://esm.sh/@supabase/supabase-js@2"
import {parseEnrichmentAction,PLANNED_PRIMARY_ENRICHMENT_SOURCE} from "../_shared/enrichment.ts"
import {safeError,SafeOperationalError} from "../_shared/security.ts"
import {assertExpectedStockId,parseDocumentAppearances,parseOverview,parseOwnership,parseSearchCandidates,TrendlyneMcpClient,verifyIdentity,type CanonicalIdentity,type TrendlyneIdentity} from "../_shared/trendlyne.ts"
import {APPROVED_COHORT_A_BATCH_1_SYMBOLS,APPROVED_COHORT_A_BATCH_2_SYMBOLS,APPROVED_COHORT_A_SYMBOLS,cohortSecurityState,executePlannedBatch,isApprovedCohortA,isRetryableProviderFailure,planCohort,SecurityExecutionError,type RefreshDomain,type SecurityRefreshPlan} from "../_shared/cohort-orchestrator.ts"

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"}
const reply=(status:number,body:Record<string,unknown>)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}})
const sha=async(value:unknown)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(value))))).map(x=>x.toString(16).padStart(2,"0")).join("")
type Admin=ReturnType<typeof createClient>
interface RequestBody{action?:unknown;portfolioId?:unknown;securityIds?:unknown;sourceCode?:unknown;dryRun?:unknown;documentSecurityIds?:unknown;batchNumber?:unknown}
interface Security extends CanonicalIdentity{readonly id:string}
const providerFailureCode=(error:unknown)=>{const message=error instanceof Error?error.message:"";return ["AMBIGUOUS_PROVIDER_IDENTITY","NO_EXACT_PROVIDER_IDENTITY","CONFLICTING_PROVIDER_IDENTITY","UNEXPECTED_PROVIDER_SECURITY","UNEXPECTED_PROVIDER_DOCUMENT_SECURITY","PROVIDER_IDENTITY_ALREADY_MAPPED","PROVIDER_TIMEOUT","PROVIDER_NETWORK_ERROR","PROVIDER_PROTOCOL_ERROR","PROVIDER_RPC_ERROR","PROVIDER_RESULT_MISSING","PROVIDER_HTTP_400","PROVIDER_HTTP_401","PROVIDER_HTTP_403","PROVIDER_HTTP_404","PROVIDER_HTTP_405","PROVIDER_HTTP_406","PROVIDER_HTTP_408","PROVIDER_HTTP_415","PROVIDER_HTTP_429","PROVIDER_HTTP_500","PROVIDER_HTTP_502","PROVIDER_HTTP_503","PROVIDER_HTTP_504"].find(code=>message.includes(code))??"PROVIDER_REQUEST_FAILED"}
const refreshDomainCode:Record<RefreshDomain,string>={IDENTITY:"VERIFIED_IDENTITY",FUNDAMENTALS:"TTM_FUNDAMENTALS",OWNERSHIP:"OWNERSHIP",DOCUMENTS:"DOCUMENT_DISCOVERY"}

async function sourceRecord(admin:Admin,runId:string,kind:string,externalId:string,payload:Record<string,unknown>){
  const payloadHash=await sha(payload),row={source_code:PLANNED_PRIMARY_ENRICHMENT_SOURCE,ingestion_run_id:runId,record_kind:kind,external_record_id:externalId,payload_hash:payloadHash,raw_payload:payload,terms_snapshot:{approval_source:"OWNER_APPROVED_STAGE_7_1C"}}
  const inserted=await admin.from("data_source_records").upsert(row,{onConflict:"source_code,record_kind,external_record_id,payload_hash",ignoreDuplicates:true}).select("id").maybeSingle();if(inserted.error)throw inserted.error;if(inserted.data)return inserted.data.id
  const existing=await admin.from("data_source_records").select("id").eq("source_code",row.source_code).eq("record_kind",kind).eq("external_record_id",externalId).eq("payload_hash",payloadHash).single();if(existing.error)throw existing.error;return existing.data.id as string
}
async function putFundamentals(admin:Admin,runId:string,securityId:string,stockId:string,metrics:ReturnType<typeof parseOverview>["metrics"]){
  const recordId=await sourceRecord(admin,runId,"FUNDAMENTAL_SNAPSHOT",`${stockId}:overview`,{stock_id:stockId,metrics})
  for(const metric of metrics){const result=await admin.from("fundamental_observations").upsert({security_id:securityId,metric_code:metric.code,source_record_id:recordId,source_code:PLANNED_PRIMARY_ENRICHMENT_SOURCE,numeric_value:metric.value,unit:metric.unit,period_type:metric.periodType,consolidation_scope:null,observed_at:null,fresh_until:new Date(Date.now()+86400000).toISOString(),evidence_status:metric.evidenceStatus},{onConflict:"security_id,metric_code,source_code,period_end,period_type,consolidation_scope,source_record_id",ignoreDuplicates:true});if(result.error)throw result.error}
}
async function putOwnership(admin:Admin,runId:string,securityId:string,stockId:string,items:ReturnType<typeof parseOwnership>){
  const recordId=await sourceRecord(admin,runId,"AGGREGATE_OWNERSHIP",`${stockId}:shareholding`,{stock_id:stockId,aggregate_ownership:items})
  for(const item of items){const result=await admin.from("fundamental_observations").upsert({security_id:securityId,metric_code:item.code,source_record_id:recordId,source_code:PLANNED_PRIMARY_ENRICHMENT_SOURCE,numeric_value:item.value,unit:item.unit,period_end:item.periodEnd,period_type:item.periodEnd?"QUARTER":null,consolidation_scope:null,observed_at:null,fresh_until:new Date(Date.now()+7776000000).toISOString(),evidence_status:"AVAILABLE"},{onConflict:"security_id,metric_code,source_code,period_end,period_type,consolidation_scope,source_record_id",ignoreDuplicates:true});if(result.error)throw result.error}
}
async function putDocuments(admin:Admin,runId:string,security:Security,identity:TrendlyneIdentity,text:string){
  const appearances=parseDocumentAppearances(text).slice(0,10)
  for(const appearance of appearances){
    assertExpectedStockId(identity.stockId,appearance.stockId)
    if(appearance.symbol!==identity.symbol)throw new Error("UNEXPECTED_PROVIDER_DOCUMENT_SECURITY")
    const payload={stock_id:identity.stockId,provider_document_id:appearance.providerDocumentId,company_name:appearance.companyName,symbol:appearance.symbol,document_type:appearance.documentType,published_at:appearance.publishedAt,body_retained:false}
    const recordId=await sourceRecord(admin,runId,"RESEARCH_DOCUMENT_APPEARANCE",appearance.providerDocumentId,payload),metadataHash=await sha({source:PLANNED_PRIMARY_ENRICHMENT_SOURCE,stock_id:identity.stockId,provider_document_id:appearance.providerDocumentId})
    const existingDocument=await admin.from("research_documents").select("id").eq("security_id",security.id).eq("metadata_identity_hash",metadataHash).maybeSingle();if(existingDocument.error)throw existingDocument.error
    let documentId=existingDocument.data?.id as string|undefined
    if(!documentId){const inserted=await admin.from("research_documents").insert({security_id:security.id,document_type:appearance.documentType,published_at:appearance.publishedAt,metadata_identity_hash:metadataHash,identity_basis:"REVIEW_REQUIRED",identity_status:"REVIEW_REQUIRED",identity_evidence:{provider_document_id:appearance.providerDocumentId,provider_stock_id:identity.stockId,canonical_identity_not_established:true}}).select("id").single();if(inserted.error)throw inserted.error;documentId=inserted.data.id}
    const existingSource=await admin.from("research_document_sources").select("id").eq("source_code",PLANNED_PRIMARY_ENRICHMENT_SOURCE).eq("provider_document_id",appearance.providerDocumentId).maybeSingle();if(existingSource.error)throw existingSource.error
    if(!existingSource.data){const source=await admin.from("research_document_sources").insert({research_document_id:documentId,source_code:PLANNED_PRIMARY_ENRICHMENT_SOURCE,source_record_id:recordId,provider_document_id:appearance.providerDocumentId,source_title:appearance.documentType,source_published_at:appearance.publishedAt,retrieved_at:new Date().toISOString(),extraction_method:"MCP_SEMANTIC_SEARCH_HEADER",extraction_version:"1",extraction_provenance:{body_retained:false,header_verified:true},source_status:"REVIEW_REQUIRED"});if(source.error)throw source.error}
  }
  return appearances.length
}

Deno.serve(async request=>{
  if(request.method==="OPTIONS")return new Response("ok",{headers:cors});if(request.method!=="POST")return reply(405,{error:"Method not allowed."})
  const authorization=request.headers.get("Authorization");if(!authorization)return reply(401,{error:"Authentication required."})
  const supabaseUrl=Deno.env.get("SUPABASE_URL"),anonKey=Deno.env.get("SUPABASE_ANON_KEY"),serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),mcpUrl=Deno.env.get("TRENDLYNE_MCP_URL");if(!supabaseUrl||!anonKey||!serviceKey)return reply(500,{error:"Supabase server configuration is incomplete."})
  try{
    const body=await request.json() as RequestBody,action=parseEnrichmentAction(body.action);if(!action)throw new SafeOperationalError("INVALID_ACTION","Unknown enrichment action.",400)
    const user=createClient(supabaseUrl,anonKey,{global:{headers:{Authorization:authorization}}}),auth=await user.auth.getUser();if(auth.error||!auth.data.user)throw new SafeOperationalError("AUTHENTICATION_REQUIRED","Invalid authenticated session.",401)
    const ids=Array.isArray(body.securityIds)&&body.securityIds.every(x=>typeof x==="string")?[...new Set(body.securityIds as string[])]:[]
    if(action==="READ_CACHE"){if(!ids.length)return reply(200,{observations:[]});const cached=await user.from("current_security_enrichment_v1").select("*").in("security_id",ids);if(cached.error)throw cached.error;return reply(200,{observations:cached.data??[]})}
    if(typeof body.portfolioId!=="string")throw new SafeOperationalError("INVALID_PORTFOLIO","portfolioId is required.",400);if(action!=="REFRESH_COHORT")throw new SafeOperationalError("LEGACY_REFRESH_RETIRED","Provider refreshes must use the hardened cohort orchestrator.",409);if(!ids.length||ids.length>25)throw new SafeOperationalError("INVALID_REFRESH_SCOPE","Refresh scope exceeds its approved boundary.",400)
    const admin=createClient(supabaseUrl,serviceKey,{auth:{persistSession:false}}),portfolio=await admin.from("portfolios").select("id").eq("id",body.portfolioId).eq("user_id",auth.data.user.id).single();if(portfolio.error)throw new SafeOperationalError("PORTFOLIO_NOT_FOUND","Portfolio not found.",404)
    const sourceCode=typeof body.sourceCode==="string"?body.sourceCode:PLANNED_PRIMARY_ENRICHMENT_SOURCE;if(sourceCode!==PLANNED_PRIMARY_ENRICHMENT_SOURCE)throw new SafeOperationalError("UNSUPPORTED_SOURCE","Only the approved provider is supported.",400)
    const source=await admin.from("data_sources").select("is_active,entitlement_verified,retention_rights_verified").eq("code",sourceCode).single();if(source.error)throw new SafeOperationalError("SOURCE_NOT_FOUND","Enrichment source is not registered.",404)
    const control=await admin.from("provider_ingestion_controls").select("ingestion_enabled,scheduler_enabled,daily_internal_attempt_limit,per_run_internal_attempt_limit,policy_version").eq("source_code",sourceCode).single();if(control.error)throw new SafeOperationalError("PROVIDER_CONTROL_UNAVAILABLE","Provider safety controls are unavailable.",503)
    if(!control.data.ingestion_enabled){if(body.dryRun!==true)await admin.from("data_ingestion_runs").insert({source_code:sourceCode,portfolio_id:body.portfolioId,operation:action,orchestration_type:"BOUNDED_REFRESH",trigger_source:"OWNER",requested_by:auth.data.user.id,status:"CONFIGURATION_PENDING",completed_at:new Date().toISOString(),requested_count:ids.length,skipped_count:ids.length,policy_version:control.data.policy_version,metadata:{reason:"PROVIDER_INGESTION_DISABLED"}});return reply(409,{code:"PROVIDER_INGESTION_DISABLED",error:"Provider ingestion is disabled.",dryRun:body.dryRun===true,providerCalls:0,budgetConsumed:0})}
    if((action!=="REFRESH_COHORT"||body.dryRun!==true)&&(!mcpUrl||!source.data.is_active||!source.data.entitlement_verified||!source.data.retention_rights_verified)){await admin.from("data_ingestion_runs").insert({source_code:sourceCode,operation:action,requested_by:auth.data.user.id,status:"CONFIGURATION_PENDING",completed_at:new Date().toISOString(),requested_count:ids.length,metadata:{reason:"TRUSTED_PROVIDER_CONFIGURATION_INCOMPLETE"}});return reply(409,{code:"SOURCE_CONFIGURATION_PENDING",error:"The trusted provider configuration is incomplete."})}
    const holdings=await admin.from("current_holdings").select("security_id").eq("portfolio_id",body.portfolioId).in("security_id",ids);if(holdings.error)throw holdings.error;const held=new Set((holdings.data??[]).map(x=>x.security_id));if(ids.some(id=>!held.has(id)))throw new SafeOperationalError("SECURITY_NOT_HELD","Every requested security must be an open holding.",403)
    const securities=await admin.from("securities").select("id,name,symbol,isin,asset_class").in("id",ids);if(securities.error)throw securities.error;if((securities.data??[]).some(x=>x.asset_class!=="EQUITY"))throw new SafeOperationalError("EQUITY_ONLY","The pilot accepts equities only.",400)
    const identifiers=await admin.from("security_identifiers").select("security_id,identifier_value").eq("identifier_type","BSE_CODE").in("security_id",ids),bse=new Map((identifiers.data??[]).map(x=>[x.security_id,x.identifier_value])),cohortOrder=new Map<string,number>(APPROVED_COHORT_A_SYMBOLS.map((symbol,index)=>[symbol,index]));const rows=(securities.data??[]).map(x=>({id:x.id,name:x.name,symbol:x.symbol,isin:x.isin,bseCode:bse.get(x.id)??null})).sort((left,right)=>(cohortOrder.get(left.symbol)??Number.MAX_SAFE_INTEGER)-(cohortOrder.get(right.symbol)??Number.MAX_SAFE_INTEGER)) as Security[]
    if(action==="REFRESH_COHORT"){
      if(ids.length!==25||!isApprovedCohortA(rows.map(row=>row.symbol)))throw new SafeOperationalError("INVALID_COHORT_SCOPE","Cohort refresh requires the exact 25 owner-approved securities.",400)
      const documentIds=Array.isArray(body.documentSecurityIds)&&body.documentSecurityIds.every(x=>typeof x==="string")?[...new Set(body.documentSecurityIds as string[])]:[];if(documentIds.length>3||documentIds.some(id=>!ids.includes(id)))throw new SafeOperationalError("INVALID_DOCUMENT_SCOPE","Document discovery is limited to three cohort securities.",400)
      const now=new Date(),identity=await admin.from("security_identity_observations").select("security_id,created_at").eq("source_code",sourceCode).eq("evidence_status","MATCHED").in("security_id",ids),fundamentals=await admin.from("fundamental_observations").select("security_id,metric_code,fresh_until").eq("source_code",sourceCode).in("security_id",ids),documents=await admin.from("research_documents").select("security_id,created_at").in("security_id",documentIds),usage=await admin.from("provider_usage_events").select("actual_internal_units").eq("source_code",sourceCode).eq("accounting_class","PROVIDER_TOOL_ATTEMPT").gte("attempted_at",new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate())).toISOString());if(identity.error||fundamentals.error||documents.error||usage.error)throw new SafeOperationalError("COHORT_PLAN_UNAVAILABLE","Cached cohort evidence could not be planned.",503)
      const identityBy=new Map((identity.data??[]).map(row=>[row.security_id,new Date(new Date(row.created_at).getTime()+180*86400000).toISOString()])),fundamentalCodes=new Set(["MARKET_CAP_PROVIDER_RAW","PE_TTM","PBV_ADJUSTED_PROVIDER","REVENUE_TTM","NET_PROFIT_TTM","CFO_ANNUAL","ROE_ANNUAL"]),ownershipCodes=new Set(["SHAREHOLDING_PROMOTER_PERCENT","SHAREHOLDING_FII_FPI_PERCENT","SHAREHOLDING_DII_PERCENT","SHAREHOLDING_PUBLIC_PERCENT"])
      const minimumFresh=(securityId:string,codes:Set<string>)=>{const latestByCode=new Map<string,number>();for(const row of fundamentals.data??[]){if(row.security_id!==securityId||!codes.has(row.metric_code)||!row.fresh_until)continue;const value=Date.parse(row.fresh_until as string);if(Number.isFinite(value)&&value>(latestByCode.get(row.metric_code)??0))latestByCode.set(row.metric_code,value)}return latestByCode.size===codes.size?new Date(Math.min(...latestByCode.values())).toISOString():null},documentFresh=new Map((documents.data??[]).map(row=>[row.security_id,new Date(new Date(row.created_at).getTime()+7*86400000).toISOString()]))
      const dailyObservedUsage=(usage.data??[]).reduce((sum,row)=>sum+row.actual_internal_units,0),states=rows.map(row=>cohortSecurityState({id:row.id,symbol:row.symbol,assetClass:"EQUITY"},{securityId:row.id,identityFreshUntil:identityBy.get(row.id)??null,fundamentalFreshUntil:minimumFresh(row.id,fundamentalCodes),ownershipFreshUntil:minimumFresh(row.id,ownershipCodes),documentsFreshUntil:documentFresh.get(row.id)??null},documentIds.includes(row.id),now)),plan=planCohort(states,{dailyLimit:control.data.daily_internal_attempt_limit,perRunLimit:control.data.per_run_internal_attempt_limit,retryReservePercent:.2,maxRetryReserve:12,identitySearchCalls:2}),projectedDailyUsage=dailyObservedUsage+plan.worstCaseAttempts,budgetEligible=projectedDailyUsage<=control.data.daily_internal_attempt_limit
      if(body.dryRun===true)return reply(200,{dryRun:true,providerCalls:0,budgetConsumed:0,dailyObservedUsage,projectedDailyUsage,budgetEligible,plan})
      if(body.batchNumber!==1&&body.batchNumber!==2)throw new SafeOperationalError("INVALID_BATCH_SELECTION","Live cohort execution requires one approved logical batch.",400)
      const expectedSymbols=body.batchNumber===1?APPROVED_COHORT_A_BATCH_1_SYMBOLS:APPROVED_COHORT_A_BATCH_2_SYMBOLS,expectedSet=new Set<string>(expectedSymbols),candidate=body.batchNumber===1?plan.batches[0]:plan.batches.length===1?plan.batches[0]:plan.batches[1],candidateSymbols=candidate?.securities.map(item=>item.symbol)??[],waveOneFresh=plan.securities.filter(item=>APPROVED_COHORT_A_BATCH_1_SYMBOLS.includes(item.symbol as typeof APPROVED_COHORT_A_BATCH_1_SYMBOLS[number])).every(item=>item.baseCalls===0);if(!candidate||candidateSymbols.length!==expectedSet.size||candidateSymbols.some(symbol=>!expectedSet.has(symbol))||(body.batchNumber===2&&!waveOneFresh))throw new SafeOperationalError("BATCH_SEQUENCE_INVALID","The selected logical batch is not currently eligible for execution.",409);const selectedBatch={...candidate,batchNumber:body.batchNumber};if(dailyObservedUsage+selectedBatch.reservedAttempts>control.data.daily_internal_attempt_limit)throw new SafeOperationalError("DAILY_LIMIT_EXCEEDED","The selected batch exceeds the remaining daily safety budget.",429)
      if(!mcpUrl)throw new SafeOperationalError("SOURCE_CONFIGURATION_PENDING","The trusted provider configuration is incomplete.",409)
      const rowById=new Map(rows.map(row=>[row.id,row])),known=await admin.from("security_identity_observations").select("security_id,provider_instrument_id,observed_name,observed_symbol,observed_isin").eq("source_code",sourceCode).eq("evidence_status","MATCHED").in("security_id",ids);if(known.error)throw known.error;const knownBy=new Map((known.data??[]).map(row=>[row.security_id,{stockId:row.provider_instrument_id as string,name:row.observed_name as string,symbol:row.observed_symbol as string,bseCode:null,isin:row.observed_isin as string|null}])),policies=await admin.from("refresh_domain_policies").select("data_domain,freshness_seconds,cooldown_seconds").eq("source_code",sourceCode).is("effective_to",null).eq("is_enabled",true);if(policies.error)throw policies.error;const policyByDomain=new Map((policies.data??[]).map(policy=>[policy.data_domain,policy])),batchResults:Record<string,unknown>[]=[]
      for(const batch of [selectedBatch]){let runId="",reservationId="",leaseHolder="",mcp:TrendlyneMcpClient|undefined,retriesLeft=batch.retryReserve,acceptedSecurities=0;const itemIds=new Map<string,string>(),finishedItemIds=new Set<string>()
        await executePlannedBatch(batch,{reserve:async attempts=>{const run=await admin.from("data_ingestion_runs").insert({source_code:sourceCode,portfolio_id:body.portfolioId,operation:"REFRESH_COHORT",orchestration_type:"COHORT",trigger_source:"OWNER",requested_by:auth.data.user.id,status:"RUNNING",requested_count:batch.securities.length,estimated_call_count:batch.baseCalls,reserved_call_count:attempts,policy_version:control.data.policy_version,metadata:{cohort:"A",batch:batch.batchNumber}}).select("id").single();if(run.error)throw run.error;runId=run.data.id;const runItems=batch.securities.flatMap(item=>(Object.entries(item.domains) as [RefreshDomain,string][]).filter(([,status])=>status==="REQUIRED").map(([domain])=>({ingestion_run_id:runId,security_id:item.securityId,data_domain:refreshDomainCode[domain],status:"PLANNED"}))),inserted=await admin.from("data_ingestion_run_items").insert(runItems).select("id,security_id,data_domain");if(inserted.error)throw inserted.error;for(const row of inserted.data??[])itemIds.set(`${row.security_id}:${row.data_domain}`,row.id);const reserved=await admin.rpc("reserve_provider_budget_v1",{p_source_code:sourceCode,p_ingestion_run_id:runId,p_reservation_key:`${runId}:COHORT`,p_estimated_units:attempts,p_reservation_seconds:900});if(reserved.error||!reserved.data?.[0]?.reserved)throw new Error(reserved.data?.[0]?.reason_code??"BUDGET_RESERVATION_FAILED");reservationId=reserved.data[0].reservation_id;return{id:reservationId}},acquireLease:async()=>{leaseHolder=crypto.randomUUID();const lease=await admin.rpc("acquire_data_ingestion_lease_v1",{p_source_code:sourceCode,p_operation:"REFRESH_COHORT",p_lease_holder:leaseHolder,p_lease_seconds:900});if(lease.error||!lease.data?.[0]?.acquired)throw new Error("REFRESH_IN_PROGRESS")},executeSecurity:async(item:SecurityRefreshPlan)=>{const security=rowById.get(item.securityId);if(!security)throw new SecurityExecutionError("SECURITY_NOT_FOUND",0,0);let attempted=0,failed=0
          const tracked=async(tool:string,args:Record<string,unknown>)=>{let retry=0;for(;;){const attemptedAt=new Date().toISOString(),idempotencyKey=`${runId}:${security.id}:${tool}:${attempted+1}`;attempted++;let value:string;try{mcp??=new TrendlyneMcpClient(mcpUrl);value=await mcp.call(tool,args)}catch(error){failed++;const code=providerFailureCode(error),usage=await admin.rpc("record_provider_usage_event_v1",{p_source_code:sourceCode,p_ingestion_run_id:runId,p_run_item_id:null,p_security_id:security.id,p_data_domain:"COHORT",p_operation_class:tool.toUpperCase(),p_accounting_class:"PROVIDER_TOOL_ATTEMPT",p_estimated_internal_units:1,p_actual_internal_units:1,p_attempted_at:attemptedAt,p_completed_at:new Date().toISOString(),p_outcome:"FAILED",p_safe_error_code:code,p_retry_attempt:retry,p_idempotency_key:idempotencyKey});if(usage.error||!isRetryableProviderFailure(code)||retry>=2||retriesLeft<=0)throw new SecurityExecutionError(usage.error?"USAGE_ACCOUNTING_FAILED":code,attempted,failed);retriesLeft--;retry++;continue}const usage=await admin.rpc("record_provider_usage_event_v1",{p_source_code:sourceCode,p_ingestion_run_id:runId,p_run_item_id:null,p_security_id:security.id,p_data_domain:"COHORT",p_operation_class:tool.toUpperCase(),p_accounting_class:"PROVIDER_TOOL_ATTEMPT",p_estimated_internal_units:1,p_actual_internal_units:1,p_attempted_at:attemptedAt,p_completed_at:new Date().toISOString(),p_outcome:"SUCCEEDED",p_safe_error_code:null,p_retry_attempt:retry,p_idempotency_key:idempotencyKey});if(usage.error)throw new SecurityExecutionError("USAGE_ACCOUNTING_FAILED",attempted,failed);return value}}
          const finishDomains=async(status:"ACCEPTED"|"FAILED",reason:string|null)=>{const completedAt=new Date();for(const [domain,state] of Object.entries(item.domains) as [RefreshDomain,string][]){if(state!=="REQUIRED")continue;const dataDomain=refreshDomainCode[domain],itemId=itemIds.get(`${security.id}:${dataDomain}`),policy=policyByDomain.get(dataDomain);if(!itemId||!policy)throw new Error("REFRESH_DOMAIN_CONFIGURATION_MISSING");const itemResult=await admin.rpc("record_refresh_item_result_v1",{p_run_item_id:itemId,p_status:status,p_safe_reason_code:reason,p_attempted_call_count:attempted,p_accepted_record_count:status==="ACCEPTED"?1:0,p_metadata:{shared_overview:item.operations.includes("OVERVIEW")}});if(itemResult.error)throw itemResult.error;finishedItemIds.add(itemId);const previous=await admin.from("security_refresh_states").select("last_success_at,consecutive_failures").eq("source_code",sourceCode).eq("security_id",security.id).eq("data_domain",dataDomain).maybeSingle();if(previous.error)throw previous.error;const freshUntil=status==="ACCEPTED"&&policy.freshness_seconds?new Date(completedAt.getTime()+policy.freshness_seconds*1000).toISOString():null,stateResult=await admin.from("security_refresh_states").upsert({source_code:sourceCode,security_id:security.id,data_domain:dataDomain,last_attempt_at:completedAt.toISOString(),last_success_at:status==="ACCEPTED"?completedAt.toISOString():previous.data?.last_success_at??null,last_evidence_change_at:status==="ACCEPTED"?completedAt.toISOString():null,fresh_until:freshUntil,next_eligible_refresh_at:status==="ACCEPTED"?freshUntil:new Date(completedAt.getTime()+policy.cooldown_seconds*1000).toISOString(),consecutive_failures:status==="ACCEPTED"?0:(previous.data?.consecutive_failures??0)+1,last_safe_error_code:reason,last_run_id:runId,refresh_status:status==="ACCEPTED"?"FRESH":previous.data?.last_success_at?"FAILED_WITH_CACHE":"FAILED_NO_CACHE"});if(stateResult.error)throw stateResult.error}}
          try{const overviewText=item.operations.includes("OVERVIEW")?await tracked("get_overview_news_corp_events",{stock_code:security.symbol,type:"overview"}):null,overview=overviewText?parseOverview(overviewText):null;let providerIdentity:TrendlyneIdentity|undefined=knownBy.get(security.id)
            if(overview){const existing=knownBy.get(security.id);if(existing){assertExpectedStockId(existing.stockId,overview.identity.stockId);providerIdentity=overview.identity}else{let candidates=parseSearchCandidates(await tracked("search_entities",{query:security.symbol,entity_type:"stock",limit:10}));if(!candidates.some(candidate=>candidate.symbol===security.symbol||(security.isin!==null&&candidate.isin===security.isin)))candidates=parseSearchCandidates(await tracked("search_entities",{query:overview.identity.name,entity_type:"stock",limit:10}));providerIdentity=verifyIdentity(security,candidates,overview);const recordId=await sourceRecord(admin,runId,"SECURITY_IDENTITY",providerIdentity.stockId,{identity:providerIdentity,candidates}),written=await admin.from("security_identity_observations").insert({security_id:security.id,source_record_id:recordId,source_code:sourceCode,provider_instrument_id:providerIdentity.stockId,observed_name:providerIdentity.name,observed_isin:providerIdentity.isin,observed_exchange:"NSE",observed_symbol:providerIdentity.symbol,evidence_status:"MATCHED",confidence:"1.0000"});if(written.error)throw written.error;knownBy.set(security.id,providerIdentity)}if(item.domains.FUNDAMENTALS==="REQUIRED")await putFundamentals(admin,runId,security.id,providerIdentity.stockId,overview.metrics)}
            if(item.domains.OWNERSHIP==="REQUIRED"&&providerIdentity)await putOwnership(admin,runId,security.id,providerIdentity.stockId,parseOwnership(await tracked("get_ownership_deals_insider_sast",{stock_code:security.symbol,type:"shareholding"})))
            if(item.domains.DOCUMENTS==="REQUIRED"&&providerIdentity)await putDocuments(admin,runId,security,providerIdentity,await tracked("get_document_search_results",{query:`${providerIdentity.name} FY26 annual report`}))
            await finishDomains("ACCEPTED",null);acceptedSecurities++;return{attempted,failed}
          }catch(error){const executionError=error instanceof SecurityExecutionError?error:new SecurityExecutionError(providerFailureCode(error),attempted,failed);try{await finishDomains("FAILED",executionError.message)}catch{throw new SecurityExecutionError("REFRESH_STATE_UPDATE_FAILED",attempted,failed)}throw executionError}
          },
          settle:async(_id,attempted,failed,released)=>{const result=await admin.rpc("settle_provider_budget_v1",{p_reservation_id:reservationId,p_consumed_units:attempted-failed,p_failed_units:failed,p_released_units:released});if(result.error)throw result.error},
          releaseLease:async()=>{const result=await admin.rpc("release_data_ingestion_lease_v1",{p_source_code:sourceCode,p_operation:"REFRESH_COHORT",p_lease_holder:leaseHolder,p_cooldown_seconds:0});if(result.error)throw result.error},
          complete:async(status,attempted,failed)=>{if(!runId)return;for(const itemId of itemIds.values()){if(finishedItemIds.has(itemId))continue;const skipped=await admin.rpc("record_refresh_item_result_v1",{p_run_item_id:itemId,p_status:"SKIPPED_BUDGET",p_safe_reason_code:"BATCH_ABORTED",p_attempted_call_count:0,p_accepted_record_count:0,p_metadata:{}});if(skipped.error)throw skipped.error}const result=await admin.from("data_ingestion_runs").update({status,completed_at:new Date().toISOString(),attempted_call_count:attempted,accepted_count:acceptedSecurities,failed_count:failed,fetched_count:acceptedSecurities,skipped_count:batch.securities.length-acceptedSecurities,metadata:{cohort:"A",batch:batch.batchNumber}}).eq("id",runId);if(result.error)throw result.error}
        })
        batchResults.push({batch:batch.batchNumber,runId,reservationId})
      }
      return reply(200,{dryRun:false,plan,batches:batchResults})
    }
    throw new SafeOperationalError("COHORT_ORCHESTRATION_REQUIRED","Provider execution must use the hardened cohort orchestrator.",409)
  }catch(error){const safe=safeError(error);return reply(safe.status,{error:safe.publicMessage,code:safe.code})}
})
